name = "Sildur's Vibrant Shaders"
filename = "Sildur's+Vibrant+Shaders+v1.32+Lite.zip"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3590/70/Sildur's%20Vibrant%20Shaders%20v1.32%20Lite.zip"

hash-format = "md5"
hash = "ccedf8f59aa1d75e80e558c2afb721d0"
