name = "Client Mods"
author = "Kevin Murphy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9adece41146cca0b6e88a20e1e86f1820fb09a73dcd002588e9331582ad6c69"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
