name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fddd07b1b5d0b2ba42fdf48c643fd373debe260a6b76677ebd2f6a92cc72e837"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
