name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "242bce22b9dbce50cf3c7551a1c8daecd9878b5f1ef33407bcd22389e644a06f"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
