name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ee7b562e02fe5b7ba2758b5e9ca1182eb49d1bdb825772028682c135ae78b0e"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
