name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f54c475d3db1bbff2833f8dbbf6f7976a9c93b70227e1f882e733aabfe0046b"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
