name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17bdc583af8868470fd7eca6d40471cddfdcd1e280c67c5e88ed365c7d73c4a3"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
