name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90ded9984f16b1e024d8124e771e1e63f4cf29da46839aefb122c515d8bd55b8"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
