name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95a9c7f4951b4f388b0046a20b7482ed1b14f71cdde3c9252056aaf891d1aae1"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
