name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "306931f3df4cec7d8b8aa343a13c05c64ddc8b1f0e265a9752d65a1ad69960ca"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
