name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3d5f47345e01b5a933d8a05b56303acdcd9e2069a9a29958b9e89dea577e2eb"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
