name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdff1f7385539b44cea94bfef5cacfea28d95031b923970e89abb75d94f75163"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
