name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2303eab1571c62c94797c486885876f268c63d3ead86704c5db878f07990db43"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
