name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afd65e277607c574b85687561bed05121cbaf7884a65c61892b7d74c8b9bdd82"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
