name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bfe47f2f53399dce1ff5d7253aeda7787d07d746ccf07fc7ce4a94b320136e0"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
