name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "451a53d609745d9522979a5c60ac5afa86229a5eca897a76b26ed119e7b0f5bf"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
