name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0822e99a3bc3feaed1011eecdec1255d6987132fe6d50752ff0274421cf35f5"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
