name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aec2a1a3aa156c1ae70841d6d619c6219cb8cd1c4d2cf18b388d003d9392e13c"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
