name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "696053e115001572e104ca304547230555925e5de24068ffa3705ed7294e9202"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
