name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c73273d3a674c7c6259a718cd15f87ffdc8d6e035884029853663b2d47153b2"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
