name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0216517e9f444ca09070d5e1e6c9cf165597527a9bd2f81e838de297bb12c1e7"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
