name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4afb01f95c8301424db0b5b5ebae4ce3d110aad55cc3467f8c5b8769374def1a"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
