name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48e4a83922b2bc39a053531959c9be99e9b4f0ec4f835b45ca691669b37fe2e0"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
