name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84f0c5be96e4e6066f748eefa0a101d02a1d7cfd80b0efcc727ff90ed01aa4d3"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
