name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e528cf3cbfeeb57673931310de541035414326ad6409c7d790d82c5ddb7baba"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
