name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a056d2f42b3aac99ccf0ccd886a495fae4980586d79cc7c6edb193c9bab7641"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
