name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35ff18137d481c2614d54afe210c7380a7ae11942ab9c9ff26c86f62dcd9ee2b"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
