name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5097296360f70d1b7f34f940a28faf64c880d748cb670fae003ccb1a284a35c"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
