name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3217f0f4a467fea509e3aa2094e3d62d870df26269c4987cad486752368a6b7f"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
