name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9228603428af0820986ff17daccd92c74c684ea5a977377ca7168eb9fa0169b"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
