name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3eaa0f66ce1d8d10e423e474457ff3b821a613228c6189cfd5600c338f62c4b"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
