name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eee5672794845bb48921848f6c2eacfa7e30bb34420c6f194a2ea6df253e7634"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
