name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24d41597c593cd824ced20982848cf9c8116ecdce15bd76c52919ee4e54188b0"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
