name = "Packitywackity"
author = "Kevin Murphy"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b37ea10eb65baa50239b14a66bcfcaf8d4137c22effa3fb866a0d48577f86d3"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
